Repository Happy-Algorithms-League/hal-cgp, pull requests merged in 2020-07, with the labels that each got.

#162 Bump version to 0.1.1
  cgp/__version__.py
  setup.py
Labels: release

#167 Refactor setting of individual idx upon creation of new individuals
  cgp/ea/mu_plus_lambda.py
  cgp/population.py
  test/test_ea_mu_plus_lambda.py
  test/test_genome.py
  test/test_population.py
Labels: maintenance

#161 Unify node tests
  test/test_node.py
Labels: maintenance

#169 Simplify sorting of individuals in `mu_plus_lambda`
  cgp/ea/mu_plus_lambda.py
  test/test_ea_mu_plus_lambda.py
Labels: maintenance

#170 Simplify `create_new_parent_population` in `mu_plus_lambda`
  cgp/ea/mu_plus_lambda.py
Labels: maintenance

#187 Fix relative path to image in README
  README.rst
  docs/index.rst
Labels: bug, doc

#192 Update README.rst
  README.rst
Labels: doc

#188 Add gallery of examples to documentation
  docs/conf.py
  docs/examples.rst
  docs/index.rst
  examples/README.rst
  examples/example_caching.py
  examples/example_differential_evo_regression.py
  examples/example_evo_regression.py
  examples/example_mountain_car.py
  extra-requirements.txt
Labels: doc

#194 Fix zenodo link in README
  README.rst
Labels: doc

#195 Remove all traces of crossover/breeding pool
  README.rst
  cgp/ea/mu_plus_lambda.py
  cgp/genome.py
  cgp/population.py
  examples/example_caching.py
  examples/example_differential_evo_regression.py
  examples/example_evo_regression.py
  examples/example_mountain_car.py
  test/conftest.py
  test/test_ea_mu_plus_lambda.py
  test/test_population.py
Labels: API change

#199 Fix travis link in README
  README.rst
Labels: bug, doc

#200 Add links to source code on github to API docs
  docs/conf.py
Labels: doc

#203 Add missing notation of return value in primitives
  cgp/primitives.py
Labels: maintenance

#212 Use logical and, and reuse existing functions in helper functions of `Genome`
  cgp/genome.py
Labels: maintenance

#214 Assign parent_idx = -1 to individuals not created from other individuals via clone
  cgp/population.py
Labels: maintenance

#210 Use norm clipping instead of value clipping to avoid changing the direction of the gradient
  cgp/local_search/gradient_based.py
Labels: enhancement, maintenance

#209 Move metadata into __init__.py
  cgp/__init__.py
  cgp/__version__.py
  docs/conf.py
  setup.py
Labels: maintenance

#211 Remove unused function `_is_active_input_gene`
  cgp/genome.py
Labels: maintenance

#213 Fix parameters being reininitialized in Genome.mutate()
  cgp/genome.py
  test/conftest.py
  test/test_genome.py
Labels: bug, high priority

#216 Fix keywords and short description
  cgp/__init__.py
  setup.py
Labels: maintenance

#205 Use figures from examples in documentation
  .travis.yml
  docs/Makefile
  docs/conf.py
  examples/example_mountain_car.py
Labels: doc

#217 Reduce mutation rate in evo regression example to achieve convergence
  examples/example_evo_regression.py
Labels: bug
