Repository Happy-Algorithms-League/hal-cgp, pull requests merged in 2020-11, with the labels that each got.

#241 Make sure cache consistency uses finite return values
  cgp/utils.py
  test/test_utils.py
Labels: enhancement

#247 Bump version number to 0.2.0 to prepare for release
  cgp/__init__.py
Labels: release

#248 Use release version of sphinx-gallery
  extra-requirements.txt
Labels: maintenance
