Repository Happy-Algorithms-League/hal-cgp, pull requests merged in 2021-01, with the labels that each got.

#264 Reset parameters when the corresponding node is created by mutation of a genome
  cgp/genome.py
  test/test_node.py
Labels: enhancement

#263 Improved caching decorator
  cgp/utils.py
  examples/example_fec_caching.py
  setup.py
  test/test_utils.py
Labels: enhancement

#270 Remove support for calling graph directly
  cgp/cartesian_graph.py
  cgp/node.py
  test/test_cartesian_graph.py
  test/test_node.py
Labels: maintenance

#273 Fix error message wrong size passed to to_torch/to_numpy graphs
  cgp/cartesian_graph.py
Labels: enhancement

#272 Also use all args and kwargs when computing fec cache key
  cgp/utils.py
  test/test_utils.py
Labels: bug, high priority

#275 Remove outdated n_processes argument in hl_api
  cgp/hl_api.py
Labels: maintenance

#280 Check number of objectives matches number of specified hurdle percentiles
  cgp/ea/mu_plus_lambda.py
Labels: enhancement

#281 Make levels_back parameter optional
  cgp/genome.py
  cgp/node_validation.py
  test/test_cartesian_graph.py
  test/test_genome.py
  test/test_individual.py
  test/test_local_search.py
  test/test_node.py
Labels: API change
